package com.workbridge.backend.service;
import org.springframework.stereotype.Service;

import com.workbridge.backend.dto.GenerateMessageRequest;
import com.workbridge.backend.dto.GenerateMessageResponse;
import com.workbridge.backend.dto.GeneratedMessage;
import com.workbridge.backend.router.AIRouter;

@Service
public class MessageService {
    private final AIRouter router;

    public MessageService(AIRouter router) {
        this.router = router;
    }

    public GenerateMessageResponse generateMessage(GenerateMessageRequest request) {

        GeneratedMessage generatedMessage = router.generate(
            request.getProvider(),
            request.getRelationshipLevel(),
            request.getMessage(),
            request.getScenario()
        );

    return new GenerateMessageResponse(
            generatedMessage.getFormattedMessage(),
            "Generated by " + generatedMessage.getProvider() + " 🤖");
    }
}